Repository PDG2023/GameSync.App, pull requests merged in 2023-08, with the labels that each got.

#14 Improving the landing page
  GameSync.Api/wwwroot/coming-soon.html
  GameSync.Api/wwwroot/img/bg.jpg
Labels: enhancement

#26 fix: 🐛 fixed 404 on refresh, #25
  GameSync.Front/src/app/app.module.ts
Labels: bug

#28 fix: :bug: switched to hash strategy
  GameSync.Front/src/app/app.module.ts
Labels: bug

#29 Improving landing page
  GameSync.Api/wwwroot/coming-soon.html
  GameSync.Api/wwwroot/css/landingStyle.css
  GameSync.Api/wwwroot/css/landingStyle.min.css
  GameSync.Api/wwwroot/img/bg.webp
  GameSync.Api/wwwroot/img/f2.webp
  GameSync.Api/wwwroot/img/f3.webp
  GameSync.Api/wwwroot/img/ferati.webp
  GameSync.Api/wwwroot/img/flavio.webp
  GameSync.Api/wwwroot/img/jorand.webp
  GameSync.Api/wwwroot/img/orig/bg.jpg
  GameSync.Api/wwwroot/img/orig/f2.png
  GameSync.Api/wwwroot/img/orig/f3.jpg
  GameSync.Api/wwwroot/img/orig/ferati.png
  GameSync.Api/wwwroot/img/orig/flavio.jpg
  GameSync.Api/wwwroot/img/orig/jorand.png
  GameSync.Api/wwwroot/img/orig/welcome.png
  GameSync.Api/wwwroot/img/welcome.webp
  GameSync.Api/wwwroot/js/landingScript.js
  GameSync.Api/wwwroot/js/landingScript.min.js
Labels: enhancement, wip

#101 Improving / revamping landing page
  GameSync.Api/wwwroot/coming-soon.html
  GameSync.Api/wwwroot/css/landingStyle.css
  GameSync.Api/wwwroot/css/landingStyle.min.css
  GameSync.Api/wwwroot/js/landingScript.js
  GameSync.Api/wwwroot/js/landingScript.min.js
Labels: enhancement
